### ISSUE TITLE
Not showing up

### ISSUE THREAD

**Issue by fmlirl** [laxyapahuja/bunken#5]
Not showing up in chrome V 94.0.4606.71 or Opera V:79.0.4143.61. Goodreads is apparently testing a new design, which I've opted out of, but Bunken still isn't available

![opera](https://user-images.githubusercontent.com/90847013/135849226-5ba1ef7d-39d9-445e-a03d-03cf4c74c1f3.png)
![chrome](https://user-images.githubusercontent.com/90847013/135849237-c3e1616b-c1d3-4775-9ca0-f53575c1fa42.png)

**Comment by laxyapahuja** [comment]
My domain nameservers got changed by themselves. I've fixed it now. Should work. Thanks for bringing this up :)

**Comment by fmlirl** [comment]
Thanks! Can confirm, it's working again
