### ISSUE TITLE
Google needs Metadata vers. 3

### ISSUE THREAD

**Issue by Pocarai** [laxyapahuja/bunken#7]
This Repository still alive?
it not working for me

**Comment by sheldor1510** [comment]
Hi, could you elaborate on the issue?
It'd be great if you could attach some screenshots or error messages

**Comment by Pocarai** [comment]
Here are my problem in

**Comment by Pocarai** [comment]
Here are some problem
(using Kiwi browser for android)

> Google won't gives function for Manifest Not sure if it'll work since a error shows in extension
![IMG_20220521_115508](https://user-images.githubusercontent.com/96225118/169634585-3013db41-6349-4786-b939-e03d8e096658.jpg)

> It doesn't show results anymore It keeps saying Searching until it gone with no Results
![IMG_20220521_115810](https://user-images.githubusercontent.com/96225118/169634621-7809da6c-3a1b-4963-8db0-6c9c9d676883.jpg)

**Comment by laxyapahuja** [comment]
@Pocarai sorry for the late reply. it looks like the domain expired. i'll update it in a few days.

side note: the book you're trying to search for has a japanese name and it may be hard for it to be found on ebook sites.

**Comment by cod-lvr** [comment]
Hey @Pocarai, I want to check with you that same problem still not solved, and the extension not working anymore,

**Comment by laxyapahuja** [comment]
fixed in the newest update
