### ISSUE TITLE
Goodreads did a complete site overhaul, script no longer works.

### ISSUE THREAD

**Issue by Tenome** [laxyapahuja/bunken#8]
Site looks like this now.
![c48eabc1e2 1](https://user-images.githubusercontent.com/12216081/184289463-176e0ecd-ea7f-438c-9fd9-e65b0068ebc3.png)

**Comment by cod-lvr** [comment]
Goodreads did a complete site overhaul, hope to find a solution for this soon

**Comment by laxyapahuja** [comment]
solved in #9

**Comment by Tenome** [comment]
Can you post a screenshot of where it should be? I'm not seeing it on the redesign. Looking at the page's source, I don't see the relatedWorks element that the script references.

**Comment by Tenome** [comment]
Hmm, seems kind of hit or miss with its current position in Goodreads' new layout. Same book, different edition. Shows up in one but not the other.

https://www.goodreads.com/book/show/57891.Battle_Royale
https://www.goodreads.com/book/show/266592.Battle_Royale

https://puu.sh/JlJMG/b4b062fb50.png
https://puu.sh/JlJMJ/e9178337af.png

**Comment by Tenome** [comment]
It looks like Goodreads reverted back to the old site design. I guess the feedback was so negative that they put it on hold for now.

**Comment by Tenome** [comment]
Goodreads finally forced their UI update, so the script doesn't work anymore (same problems as mentioned in earlier posts). Oh well, guess I'll disable it for now.
